---
abstract: 'use HTTP with C<IO::Async>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  HTTP::Cookies: 0
  IO::Async::Test: 0
  Test::Identity: 0
  Test::More: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-HTTP
provides:
  Net::Async::HTTP:
    file: lib/Net/Async/HTTP.pm
    version: 0.24
  Net::Async::HTTP::Protocol:
    file: lib/Net/Async/HTTP/Protocol.pm
    version: 0.24
requires:
  Future: 0.13
  Future::Utils: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  HTTP::Response: 0
  IO::Async::Loop: 0.56
  IO::Async::Protocol::Stream: 0.58
  IO::Async::Stream: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.24
